analyzer:
  errors:
    unused_element_parameter: ignore
    unused_result: ignore
  exclude:
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**
include: package:flutter_lints/flutter.yaml

linter:
   
  rules:
    prefer_const_constructors: true  # Uncomment to enable the `prefer_single_quotes` rule