// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJ745k9Ib9yY2qTYdADOQAwr2EApLPCEI',
    appId: '1:236969530242:web:09be5c73c0112c872b359b',
    messagingSenderId: '236969530242',
    projectId: 'rafeeq-d50ef',
    authDomain: 'rafeeq-d50ef.firebaseapp.com',
    storageBucket: 'rafeeq-d50ef.firebasestorage.app',
    measurementId: 'G-L99KH0QXGB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWsDlAKczb_-M1zQGxSv5xzZNrPW1Hr_c',
    appId: '1:236969530242:android:43e5159102fb0c2f2b359b',
    messagingSenderId: '236969530242',
    projectId: 'rafeeq-d50ef',
    storageBucket: 'rafeeq-d50ef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDV4H3k80rLPhCrHhJH-UUqA5TrNqByYfg',
    appId: '1:236969530242:ios:6ff792aa9070d6852b359b',
    messagingSenderId: '236969530242',
    projectId: 'rafeeq-d50ef',
    storageBucket: 'rafeeq-d50ef.firebasestorage.app',
    iosBundleId: 'com.example.rafeeq',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDV4H3k80rLPhCrHhJH-UUqA5TrNqByYfg',
    appId: '1:236969530242:ios:6ff792aa9070d6852b359b',
    messagingSenderId: '236969530242',
    projectId: 'rafeeq-d50ef',
    storageBucket: 'rafeeq-d50ef.firebasestorage.app',
    iosBundleId: 'com.example.rafeeq',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJ745k9Ib9yY2qTYdADOQAwr2EApLPCEI',
    appId: '1:236969530242:web:f95f06c44179f5ae2b359b',
    messagingSenderId: '236969530242',
    projectId: 'rafeeq-d50ef',
    authDomain: 'rafeeq-d50ef.firebaseapp.com',
    storageBucket: 'rafeeq-d50ef.firebasestorage.app',
    measurementId: 'G-L686L7QV8M',
  );
}
